name: Validate Pull Request Checklist

on:
  pull_request:
    types: [opened, edited, synchronize] # Trigger workflow on PR events
  workflow_dispatch:
    inputs:
      question_1:
        description: 'Question 1'
        required: true
        default: 'yes'
      question_2:
        description: 'Question 2'
        required: false      
        default: 'no'
      question_3:
        description: 'Question 3'
        required: false
        default: 'maybe'   

jobs:
  validate-checklist:
    runs-on: ubuntu-latest # Use Ubuntu virtual machine

    steps:
    - name: Check PR Description
      id: check-description
      uses: actions/github-script@v6 # Run custom JavaScript code
      with:
        script: |
          const checklist = [
            "- [x] ${{ github.event.inputs.question_1 }}:", // First checklist item
            "- [x] ${{ github.event.inputs.question_2 }}:", // Second checklist item
            "- [x] ${{ github.event.inputs.question_3 }}:", // Third checklist item
          ];

          const prBody = context.payload.pull_request.body || ""; // Get PR description
          const missingItems = checklist.filter(item => !prBody.includes(item)); // Check for missing items

          if (missingItems.length > 0) {
            core.setFailed(`Checklist incomplete. Missing items: ${missingItems.join(", ")}`); // Fail if incomplete
          } else {
            core.info("Checklist is complete."); // Log success if complete
          }
